import { SONGS_IMAGES } from "./constants";


export const TRACK_LIST = [
  {
    name: 'Do Tańca Kawałek',
    mp3Name: 'do_tanca_kawalek',
    artist: 'Poparzeni kawą trzy',
    imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: 'Kici Kici miał',
    mp3Name: 'kici_kici_mial',
    artist: 'Marcus',
    imgSrc: SONGS_IMAGES.marcus,
  },
  {
    name: 'Konik na biegunach',
    mp3Name: 'konik_na_biegunach',
    artist: 'Urszula',
    imgSrc: SONGS_IMAGES.urszula,
  },
  {
    name: 'Weź nie pytaj',
    mp3Name: 'WezNiePytaj',
    artist: 'Paweł Domagała',
    // imgSrc: SONGS_IMAGES.urszula,
  },
  {
    name: 'Mama ostrzegała',
    mp3Name: 'mama_ostrzegala',
    artist: 'Daj to głośniej',
    imgSrc: SONGS_IMAGES.DAJ_TO_GLOSNIEJ,
  },
  {
    name: 'Miła ma',
    mp3Name: 'mila_ma',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Miłość w Zakopanem',
    mp3Name: 'milosc_w_zakopanem',
    artist: 'Sławomir',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Ona by tak chciała',
    mp3Name: 'ona_by_tak_chciala',
    artist: 'Ronnie Ferrari',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Remedium',
    mp3Name: 'remedium',
    artist: 'Maryla Rodowicz',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Sway',
    mp3Name: 'sway',
    artist: 'Michael Buble',
    imgSrc: SONGS_IMAGES.buble,
  },
  {
    name: 'Bananowa Agnieszka',
    mp3Name: 'bananowa_agnieszka',
    artist: 'After Party',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Autostop',
    mp3Name: 'autoStop',
    artist: 'Karin Stanek',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Bałkanica',
    mp3Name: 'balkanica',
    artist: 'Piersi',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: 'Małgośka',
    mp3Name: 'Malgoska',
    artist: 'Maryla Rodowicz',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Baśka',
    mp3Name: 'Baska',
    artist: 'Wilki',
    // imgSrc: SONGS_IMAGES.Naydis,
  },
  {
    name: "Przekorny Los",
    mp3Name: 'PrzekornyLos',
    artist: 'Akcent',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },

  {
    name: 'Byłaś dla mnie wszystkim',
    mp3Name: 'BylasDlaMnieWszystkim',
    artist: 'Poparzeni kawą trzy',
    imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: 'Co tu się dzieje',
    mp3Name: 'CoTuSieDzieje',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Cała sala śpiewa z nami',
    mp3Name: 'CalaSala',
    artist: 'Jerzy Połomski',
  },
  {
    name: 'Chałupy welcome to',
    mp3Name: 'ChalupyWelcomeTo',
    artist: 'Zbigniew Wodecki',
  },
  {
    name: 'Co ma być to będzie',
    mp3Name: 'CoMaBycToBedzie',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Czarownica',
    mp3Name: 'Czarownica',
    artist: 'Fanatic',
    imgSrc: SONGS_IMAGES.Fanatic,
  },
  {
    name: 'Czy ten Pan i Pani',
    mp3Name: 'CzyTenPanIPani',
    artist: 'Ania Wyszkoni',
  },
  {
    name: 'Kochaj mnie',
    mp3Name: 'KochajMnie',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Do białego rana',
    mp3Name: 'DoBialegoRana',
    artist: 'Freaky Boys',
  },
  {
    name: 'Honey Honey',
    mp3Name: 'HoneyHoney',
    artist: 'Abba',
  },
  {
    name: 'Hula ula',
    mp3Name: 'HulaHula',
    artist: 'Marcus',
    imgSrc: SONGS_IMAGES.marcus,
  },
  {
    name: 'Jaki piękny świat',
    mp3Name: 'JakiPieknySwiat',
    artist: 'Boys',
    // imgSrc: SONGS_IMAGES.marcus,
  },
  {
    name: 'Kawiarenki',
    mp3Name: 'Kawiarenki',
    artist: 'Irena Jarocka',
    // imgSrc: SONGS_IMAGES.marcus,
  },
  {
    name: 'Bukiet róż',
    mp3Name: 'BukietRoz',
    artist: 'Veegas',
    // imgSrc: SONGS_IMAGES.Naydis,
  },

  {
    name: 'Za tobą pójdę jak ba bal',
    mp3Name: 'ZaTobaPojdeJakNaBal',
    artist: 'Krzysztof Krawczyk',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Łobuz',
    mp3Name: 'Lobuz',
    artist: 'Boys',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: 'Lubisz to',
    mp3Name: 'LubiszTo',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Mamma mia He's italiano",
    mp3Name: 'MammaMiaHisItaliano',
    artist: 'Elena Gheorghe',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Rock&Roll",
    mp3Name: 'Rock&Roll',
    artist: 'Electric Light Orchestra',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Mazureczka",
    mp3Name: 'Mazureczka',
    artist: 'Masters',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Miod malina",
    mp3Name: 'MiodMalina',
    artist: 'MIG',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Mleczko",
    mp3Name: 'Mleczko',
    artist: 'Energy Girls',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Najpiękne",
    mp3Name: 'Najpiekne',
    artist: 'Power Play',
    imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Nie chce spać",
    mp3Name: 'NieChceSpac',
    artist: 'Enej',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Nie płacz Ewka",
    mp3Name: 'NiePlaczEwka',
    artist: 'Perfect',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Niech żyje bal",
    mp3Name: 'NiechZyjeBal',
    artist: 'Maryla Rodowicz',
    // imgSrc: SONGS_IMAGES.powerPLay,
  },
  {
    name: "Okrutna zła i podła",
    mp3Name: 'OkrutnaZlaIPodla',
    artist: 'Poparzeni kawą trzy',
    imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Ona czuje we mnie piniądz",
    mp3Name: 'OnaCzujeWeMniePiniadz',
    artist: 'Łobuzy',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Ona jest taka cudowna",
    mp3Name: 'OnaJestTakaCudowna',
    artist: 'Piękni i młodzi',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Piąty bieg",
    mp3Name: 'PiatyBieg',
    artist: 'Budka suflera',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Prywatki",
    mp3Name: 'Prywatki',
    artist: 'Piotr Gąsowski',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Prześliczna wiolączelistka",
    mp3Name: 'PrzeslicznaWiolaczelistka',
    artist: 'Skaldowie',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Przeżyj to sam",
    mp3Name: 'PrzezyjToSam',
    artist: 'Lombard',
    imgSrc: SONGS_IMAGES.lombard,
  },
  {
    name: "Ruda tańczy jak szalona",
    mp3Name: 'RudaTanczyJakSzalona',
    artist: 'Czadoman',
    imgSrc: SONGS_IMAGES.czadoman,
  },
  {
    name: "W kinie w Lublinie",
    mp3Name: 'WKinieWLublinie',
    artist: 'Brathanki',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },
  {
    name: "Waterloo",
    mp3Name: 'Waterloo',
    artist: 'Abba',
    // imgSrc: SONGS_IMAGES.poparzeniKawaTrzy,
  },

]
